# Generated by Django 3.0.8 on 2020-09-19 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('instructions', models.TextField()),
                ('favorite', models.CharField(choices=[('N', 'Not'), ('F', 'Favorite')], default='N', max_length=1)),
                ('main_ingredient', models.CharField(choices=[('C', 'Chicken'), ('P', 'Pork'), ('B', 'Beef'), ('F', 'Fish'), ('S', 'Shellfish'), ('L', 'Lamb'), ('N', 'Pasta'), ('V', 'Vegetarian')], default='C', max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='meal date')),
                ('recipe', models.ManyToManyField(to='main_app.Recipe')),
            ],
        ),
    ]
