# Generated by Django 3.0.8 on 2020-09-22 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200921_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='main_ingredient',
            field=models.CharField(choices=[('C', 'Chicken'), ('P', 'Pork'), ('B', 'Beef'), ('F', 'Fish'), ('S', 'Shellfish'), ('L', 'Lamb'), ('N', 'Pasta'), ('V', 'Vegetarian'), ('O', 'Other')], default='C', max_length=1),
        ),
    ]
